Sugeng_Avenue/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main
from main.views import show_main, create_product_entry, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user, edit_product, delete_product, add_product_entry_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create_product_entry', create_product_entry, name='create_product_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),
    path('create-product-entry-ajax', add_product_entry_ajax, name='add_product_entry_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

class ProductEntry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    rating = models.FloatField()

main/forms.py
from django.forms import ModelForm
from main.models import ProductEntry
from django.utils.html import strip_tags

class ProductEntryForm(ModelForm):
    class Meta:
        model = ProductEntry
        fields = ["name", "price", "description", "rating"]

    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)

    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)

main/views.py
from django.shortcuts import render, redirect, reverse   # Tambahkan import redirect di baris ini
from main.forms import ProductEntryForm
from main.models import ProductEntry
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse

@login_required(login_url='/login')
def show_main(request):
    context = {
        'name': request.user.username,
        'description': 'Rp. 1.850.000',
        'rating': 'Kalcer',
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product_entry(request):
    form = ProductEntryForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product_entry = form.save(commit=False)
        product_entry.user = request.user
        product_entry.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, "create_product_entry.html", context)

def show_xml(request):
    data = ProductEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = ProductEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = ProductEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = ProductEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
        user = form.get_user()
        login(request, user)
        response = HttpResponseRedirect(reverse("main:show_main"))
        response.set_cookie('last_login', str(datetime.datetime.now()))
        return response
      else:
        messages.error(request, 'Invalid username or password.')

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product entry berdasarkan id
    product = ProductEntry.objects.get(pk = id)

    # Set product entry sebagai instance dari form
    form = ProductEntryForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    product = ProductEntry.objects.get(pk = id)
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_product_entry_ajax(request):
    name = strip_tags(request.POST.get("name"))
    price = request.POST.get("price")
    description = strip_tags(request.POST.get("description"))
    rating = request.POST.get("rating")
    user = request.user

    new_product = ProductEntry(
        name=name, price=price, 
        description=description,
        rating=rating,
        user=user
    )
    new_product.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = ProductEntry.objects.create(
            user=request.user,
            name=data["product"],
            description=data["description"],
            price=int(data["price"]),
            rating=int(data["rating"])
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/card_product.html
{% load static %}

<div class="max-w-sm mx-auto bg-white shadow-md rounded-lg overflow-hidden">
  <!-- Image of the Product -->
  <div class="relative">
    <img src="{% static 'image/sandal-jepit.png' %}" alt="Product Image" class="w-full h-56 object-cover">
    <div class="absolute top-2 right-2 flex space-x-2">
      <!-- Edit Button -->
      <a href="{% url 'main:edit_product' product_entry.pk %}" class="bg-yellow-400 hover:bg-yellow-500 text-white rounded-full p-2 transition duration-300 shadow">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
          <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
        </svg>
      </a>
      <!-- Delete Button -->
      <a href="{% url 'main:delete_product' product_entry.pk %}" class="bg-red-400 hover:bg-red-500 text-white rounded-full p-2 transition duration-300 shadow">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
        </svg>
      </a>
    </div>
  </div>

  <!-- Product Info -->
  <div class="p-6">
    <h3 class="text-lg font-semibold text-gray-800">{{ product_entry.name }}</h3>
    <p class="text-gray-600">{{ product_entry.price }}</p>
    <p class="mt-2 text-gray-500">{{ product_entry.description }}</p>

    <!-- Rating Section -->
    <div class="mt-4">
      <p class="text-sm text-gray-600">Rating</p>
      <div class="flex items-center space-x-1">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
          <path d="M9.049 2.927C9.269 2.343 10.732 2.343 10.951 2.927l1.402 3.595a1 1 0 00.95.691h3.933c.616 0 .87.79.37 1.175l-3.181 2.354a1 1 0 00-.364 1.118l1.402 3.595c.22.584-.483 1.054-1.002.7l-3.181-2.354a1 1 0 00-1.176 0l-3.181 2.354c-.519.354-1.223-.116-1.002-.7l1.402-3.595a1 1 0 00-.364-1.118L2.333 8.388c-.5-.385-.246-1.175.37-1.175h3.933a1 1 0 00.95-.691l1.402-3.595z" />
        </svg>
        <!-- Add more star icons as needed -->
      </div>
    </div>
  </div>
</div>

main/templates/create_product_entry.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Create Mood</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-gray-100">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-black">Create Product Entry</h1>
  
    <div class="bg-white shadow-md rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-2  text-gray-700">
              {{ field.label }}
            </label>
            <div class="w-full">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="flex justify-center mt-6">
          <button type="submit" class="bg-indigo-600 text-white font-semibold px-6 py-3 rounded-lg hover:bg-indigo-700 transition duration-300 ease-in-out w-full">
            Create Product Entry
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Edit Mood</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="flex flex-col min-h-screen bg-gray-100">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-black">Edit Mood Entry</h1>
  
    <div class="bg-white rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6">
          {% csrf_token %}
          {% for field in form %}
              <div class="flex flex-col">
                  <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700">
                      {{ field.label }}
                  </label>
                  <div class="w-full">
                      {{ field }}
                  </div>
                  {% if field.help_text %}
                      <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
                  {% endif %}
                  {% for error in field.errors %}
                      <p class="mt-1 text-sm text-red-600">{{ error }}</p>
                  {% endfor %}
              </div>
          {% endfor %}
          <div class="flex justify-center mt-6">
              <button type="submit" class="bg-indigo-600 text-white font-semibold px-6 py-3 rounded-lg hover:bg-indigo-700 transition duration-300 ease-in-out w-full">
                  Edit Mood Entry
              </button>
          </div>
      </form>
  </div>
  </div>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex items-center justify-center bg-gray-50">
  <div class="flex justify-between w-full max-w-4xl bg-white shadow-lg rounded-lg">
    <div class="hidden md:flex md:w-1/2 p-10 items-center justify-center bg-whie-50">
      <img src="{% static 'image/logo_sugengavenue.png' %}" alt="Sugeng Avenue" class="h-40 w-auto mx-auto object-contain" >
    </div>

    <div class="w-full md:w-1/2 p-8">
      <h2 class="text-3xl font-bold text-gray-800 mb-6">Login</h2>

      <form action="" method="POST">
        {% csrf_token %}
        <div class="mb-4">
          <label for="username" class="block text-sm font-semibold text-gray-700">Username</label>
          <input id="username" type="text" name="username" required
                 class="w-full mt-2 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
        </div>

        <div class="mb-6">
          <label for="password" class="block text-sm font-semibold text-gray-700">Password</label>
          <input id="password" type="password" name="password" required
                 class="w-full mt-2 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
        </div>

        <div class="mb-6">
          <button type="submit"
              class="w-full px-4 py-2 bg-blue-500 text-white font-semibold rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500">
              Sign in
          </button>
        </div>
      </form>

      {% if messages %}
      <div class="mt-4">
        {% for message in messages %}
          {% if message.tags == "success" %}
          <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
            <span class="block sm:inline">{{ message }}</span>
          </div>
          {% elif message.tags == "error" %}
          <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
            <span class="block sm:inline">{{ message }}</span>
          </div>
          {% else %}
          <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
            <span class="block sm:inline">{{ message }}</span>
          </div>
          {% endif %}
        {% endfor %}
      </div>
      {% endif %}

      <div class="text-center mt-4">
        <p class="text-sm text-black">
          Don't have an account yet?
          <a href="{% url 'main:register' %}" class="font-medium text-indigo-200 hover:text-indigo-300">
            Register Now
          </a>
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
<title>Sugeng Avenue</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="overflow-x-hidden px-4 md:px-8 pb-8 pt-24 min-h-screen bg-gray-100 flex flex-col">
  <div class="flex items-center justify-center mb-10">
    <div class="w-70 h-70">
      <img src="{% static 'image/logo_sugengavenue.png' %}" alt="Sugeng Avenue Logo" class="object-contain">
    </div>
    <div class="ml-6 max-w-lg text-justify">
      <h2 class="text-2xl font-bold text-indigo-600 mb-2">Sugeng Avenue E-commerce</h2>
      <p class="text-gray-700">
        Sugeng Avenue adalah sebuah platform e-commerce yang dibangun oleh seorang mahasiswa Fasilkom UI angkatan 2023. 
        Platform ini bertujuan untuk memberikan kemudahan dalam jual beli produk-produk lokal yang berkualitas, 
        dengan interface yang sederhana namun elegan. Melalui Sugeng Avenue, kami ingin membantu meningkatkan keterhubungan 
        antara konsumen dan produsen lokal.
      </p>
    </div>
  </div>
    
  <div class="flex justify-end mb-6">
    <a href="{% url 'main:create_product_entry' %}" class="bg-green-500 hover:bg-green-00 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105">
        Add New Product Entry
    </a>
    <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105" onclick="showModal();">
      Add New Product Entry by AJAX
    </button>
  </div>
  <div id="product_entry_cards"></div>
  <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
    <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
      <!-- Modal header -->
      <div class="flex items-center justify-between p-4 border-b rounded-t">
        <h3 class="text-xl font-semibold text-gray-900">
          Add New Product Entry
        </h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
          <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <!-- Modal body -->
      <div class="px-6 py-4 space-y-6 form-style">
        <form id="productEntryForm">
          <div class="mb-4">
            <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
            <input type="text" id="name" name="name" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Enter your product" required>
          </div>
          <div class="mb-4">
            <label for="price" class="block text-sm font-medium text-gray-700">Price</label>
            <input type="number" id="price" name="price" rows="3" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" required>
          </div>
          <div class="mb-4">
            <label for="description" class="block text-sm font-medium text-gray-700">Description</label>
            <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Describe your description" required></textarea>
          </div>
          <div class="mb-4">
            <label for="rating" class="block text-sm font-medium text-gray-700">Rating (1-10)</label>
            <input type="number" id="rating" name="rating" min="1" max="10" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" required>
          </div>
        </form>
      </div>
      <!-- Modal footer -->
      <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
        <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
        <button type="submit" id="submitProductEntry" form="productEntryForm" class="bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg">Save</button>
      </div>
    </div>
  </div>
  <div class="px-3 mb-1 bg-white-600"></div>
    <p class="text-black text-center">Last Login: {{last_login}}</p>
  </div>
</div>

<script>
function addProductEntry() {
  fetch("{% url 'main:add_product_entry_ajax' %}", {
    method: "POST",
    body: new FormData(document.querySelector('#productEntryForm')),
  })
  .then(response => refreshProductEntries())

  document.getElementById("productEntryForm").reset(); 
  document.querySelector("[data-modal-toggle='crudModal']").click();

  return false;
}
async function getProductEntries(){
  return fetch("{% url 'main:show_json' %}").then((res) => res.json());
}
async function refreshProductEntries() {
  document.getElementById("product_entry_cards").innerHTML = "";
  document.getElementById("product_entry_cards").className = "";
  const productEntries = await getProductEntries();
  let htmlString = "";
  let classNameString = "";

  if (productEntries.length === 0) {
      classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
      htmlString = `
          <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
              <img src="{% static 'image/sedih-banget.png' %}" alt="Sad face" class="w-32 h-32 mb-4"/>
              <p class="text-center text-gray-600 mt-4">Belum ada data product pada Sugeng Avenue.</p>
          </div>
      `;
  }
  else {
      classNameString = "columns-1 sm:columns-2 lg:columns-3 gap-6 space-y-6 w-full"
      productEntries.forEach((item) => {
        const name = DOMPurify.sanitize(item.fields.name);
        const description = DOMPurify.sanitize(item.fields.description);
          htmlString += `
          <div class="max-w-sm mx-auto bg-white shadow-md rounded-lg overflow-hidden">
            <!-- Image of the Product -->
            <div class="relative">
              <img src="{% static 'image/sandal-jepit.png' %}" alt="Product Image" class="w-full h-56 object-cover">
              <div class="absolute top-2 right-2 flex space-x-2">
                <!-- Edit Button -->
                <a href="/edit-product/${item.pk}" class="bg-yellow-400 hover:bg-yellow-500 text-white rounded-full p-2 transition duration-300 shadow">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
                    <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                  </svg>
                </a>
                <!-- Delete Button -->
                <a href="/delete/${item.pk}" class="bg-red-400 hover:bg-red-500 text-white rounded-full p-2 transition duration-300 shadow">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                  </svg>
                </a>
              </div>
            </div>

            <!-- Product Info -->
            <div class="p-6">
              <h3 class="text-lg font-semibold text-gray-800">${name}</h3>
              <p class="text-gray-600">Rp ${item.fields.price}</p>
              <p class="mt-2 text-gray-500">${description}</p>

              <!-- Rating Section -->
              <div class="mt-4">
                <p class="text-sm text-gray-600">Rating</p>
                <div class="flex items-center space-x-1">
                  ${Array.from({length: item.fields.rating}, () => `
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M9.049 2.927C9.269 2.343 10.732 2.343 10.951 2.927l1.402 3.595a1 1 0 00.95.691h3.933c.616 0 .87.79.37 1.175l-3.181 2.354a1 1 0 00-.364 1.118l1.402 3.595c.22.584-.483 1.054-1.002.7l-3.181-2.354a1 1 0 00-1.176 0l-3.181 2.354c-.519.354-1.223-.116-1.002-.7l1.402-3.595a1 1 0 00-.364-1.118L2.333 8.388c-.5-.385-.246-1.175.37-1.175h3.933a1 1 0 00.95-.691l1.402-3.595z"/>
                    </svg>`).join('')}
                </div>
              </div>
            </div>
          </div>
          `;
      });
  }
  document.getElementById("product_entry_cards").className = classNameString;
  document.getElementById("product_entry_cards").innerHTML = htmlString;
}
refreshProductEntries();
const modal = document.getElementById('crudModal');
const modalContent = document.getElementById('crudModalContent');

function showModal() {
  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');

  modal.classList.remove('hidden'); 
  setTimeout(() => {
    modalContent.classList.remove('opacity-0', 'scale-95');
    modalContent.classList.add('opacity-100', 'scale-100');
  }, 50); 
}

function hideModal() {
  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');

  modalContent.classList.remove('opacity-100', 'scale-100');
  modalContent.classList.add('opacity-0', 'scale-95');

  setTimeout(() => {
    modal.classList.add('hidden');
  }, 150); 
}

document.getElementById("cancelButton").addEventListener("click", hideModal);
document.getElementById("closeModalBtn").addEventListener("click", hideModal);

document.getElementById("productEntryForm").addEventListener("submit", (e) => {
  e.preventDefault();
  addProductEntry();
})
</script>
{% endblock content %}